apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jatnlsw9z-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:6b902633eca11dc1063bbf074da13c08b5765bac@sha256:6fa5e8cb85d352e137f1375721f390df9b32b22e0bd47243c8ffe5cfdc931d95
          name: container-image
